name: flutter_couture
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.2
  http: ^1.3.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/couture.jpg
    - images/facebook.jpg
    - images/google.jpg
    - images/1.jpg
    - images/asset/2.jpg
    - images/asset/3.jpg
    - images/asset/4.jpg
    - images/asset/5.jpg
    - images/asset/6.jpg
    - images/asset/7.jpg
    - images/asset/8.jpg
    - images/asset/9.jpg
    - images/asset/10.jpg
    - images/asset/11.jpg
    - images/asset/12.jpg
    - images/asset/13.jpg
    - images/asset/14.jpg
    - images/asset/15.jpg
    - images/asset/16.jpg
    - images/asset/17.jpg
    - images/asset/18.jpg
    - images/asset/19.jpg
    - images/asset/20.jpg
    - images/asset/21.jpg
    - images/asset/22.jpg
    - images/asset/23.jpg
    - images/asset/24.jpg
    - images/asset/25.jpg
    - images/asset/26.jpg
    - images/asset/27.jpg
    - images/asset/28.jpg
    - images/asset/29.jpg
    - images/asset/30.jpg
    - images/asset/31.jpg
    - images/asset/32.jpg
    - images/asset/33.jpg
    - images/asset/34.jpg
    - images/asset/35.jpg
    - images/asset/36.jpg
    - images/asset/37.jpg
    - images/asset/38.jpg
    - images/asset/39.jpg
    - images/asset/40.jpg
    - images/asset/41.jpg
    - images/asset/42.jpg
    - images/asset/43.jpg
    - images/asset/44.jpg
    - images/asset/45.jpg
    - images/asset/46.jpg
    - images/asset/47.jpg
    - images/asset/48.jpg
    - images/asset/49.jpg
    - images/asset/50.jpg
    - images/asset/51.jpg
    - images/asset/53.jpg
    - images/asset/54.jpg
    - images/asset/55.jpg
    - images/asset/57.jpg
    - images/asset/58.jpg
    - images/asset/59.jpg
    - images/asset/60.jpg
    - images/asset/61.jpg
    - images/asset/62.jpg
    - images/asset/63.jpg
    - images/asset/64.jpg
    - images/asset/65.jpg
    - images/asset/66.jpg
    - images/asset/67.jpg
    - images/asset/68.jpg
    - images/asset/69.jpg
    - images/asset/70.jpg
    - images/asset/71.jpg
    - images/asset/72.jpg
    - images/asset/73.jpg
    - images/asset/74.jpg
    - images/asset/75.jpg
    - images/asset/76.jpg
    - images/asset/77.jpg
    - images/asset/78.jpg
    - images/asset/79.jpg
    - images/asset/80.jpg
    - images/asset/81.jpg
    - images/asset/82.jpg
    - images/asset/83.jpg
    - images/asset/84.jpg
    - images/asset/85.jpg
    - images/asset/accessories.jpg
    - images/asset/fabricbased.jpg
    - images/asset/hometextiles.jpg
    - images/asset/kidswear.jpg
    - images/asset/kidswear2.jpg
    - images/asset/menswear2.jpg
    - images/asset/occassionwear.jpg
    - images/asset/womenswear2.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
