// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbbX4ahOzV__jc6639wS3DlPUnuVTZyIs',
    appId: '1:779905342485:web:38491e7c45708f967d021c',
    messagingSenderId: '779905342485',
    projectId: 'projet-couture-e2fbe',
    authDomain: 'projet-couture-e2fbe.firebaseapp.com',
    storageBucket: 'projet-couture-e2fbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-gwePQwuAgw72fKj6BUDK5tIU7rOMH08',
    appId: '1:779905342485:android:92a4b6613f50cd917d021c',
    messagingSenderId: '779905342485',
    projectId: 'projet-couture-e2fbe',
    storageBucket: 'projet-couture-e2fbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACpK0R3TNSuSdn20DsfYra2FtNCWZYVLI',
    appId: '1:779905342485:ios:be6a83a1775229417d021c',
    messagingSenderId: '779905342485',
    projectId: 'projet-couture-e2fbe',
    storageBucket: 'projet-couture-e2fbe.firebasestorage.app',
    iosBundleId: 'com.example.flutterCouture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACpK0R3TNSuSdn20DsfYra2FtNCWZYVLI',
    appId: '1:779905342485:ios:be6a83a1775229417d021c',
    messagingSenderId: '779905342485',
    projectId: 'projet-couture-e2fbe',
    storageBucket: 'projet-couture-e2fbe.firebasestorage.app',
    iosBundleId: 'com.example.flutterCouture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbbX4ahOzV__jc6639wS3DlPUnuVTZyIs',
    appId: '1:779905342485:web:6aed230a08e59e897d021c',
    messagingSenderId: '779905342485',
    projectId: 'projet-couture-e2fbe',
    authDomain: 'projet-couture-e2fbe.firebaseapp.com',
    storageBucket: 'projet-couture-e2fbe.firebasestorage.app',
  );
}
